apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: docker.io/nginx
          ports:
            - containerPort: 80
          resources:
              limits:
                 memory: "128Mi"
                 cpu: "500m"