services:
    postgres:
        image: 'postgres'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis'
        command: ["redis-server", "--protected-mode", "no"]
    api:
        build: ./server
        image: docker.io/helgevolga/complex_api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    worker:
        build: ./worker
        image: docker.io/helgevolga/complex_worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    client:
        build: ./client
        image: docker.io/helgevolga/complex_client
    nginx:
        depends_on:
            - api
            - client
        build: ./nginx
        ports:
            - '3050:80'